// <auto-generated />
using System;
using Jelli.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jelli.Data.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20190422183903_GuildRole")]
    partial class GuildRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Jelli.Data.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<string>("CommandPrefix");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Jelli.Data.Models.GuildRole", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<ulong?>("GuildId1");

                    b.Property<string>("RoleDisplayName");

                    b.Property<ulong>("RoleId");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId1");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("Jelli.Data.Models.GuildRole", b =>
                {
                    b.HasOne("Jelli.Data.Models.Guild", "Guild")
                        .WithMany("GuildRoles")
                        .HasForeignKey("GuildId1");
                });
#pragma warning restore 612, 618
        }
    }
}
