// <auto-generated />
using Jelli.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jelli.Data.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Jelli.Data.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<string>("CommandPrefix");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
